'use client';
import{useEffect,useState}from'react';import Link from'next/link';import{supabase}from'../../../lib/supabase';
type Btn={label:string,type:'link'|'whatsapp',value:string,message?:string,style:string};
export default function EditarIndicacao(){const[ok,setOk]=useState<boolean|null>(null),[d,setD]=useState<any>(null),[msg,setMsg]=useState('');
useEffect(()=>{(async()=>{const{data:{user}}=await supabase.auth.getUser();if(!user){setOk(false);return}const{data:a}=await supabase.rpc('is_site_admin');setOk(!!a);if(a){const{data}=await supabase.from('recommendation_settings').select('*').eq('slug','procedimentos-esteticos').single();setD(data)}})()},[]);
const set=(k:string,v:any)=>setD((x:any)=>({...x,[k]:v}));
async function save(){setMsg('Salvando...');const{slug,updated_at,...payload}=d;const{error}=await supabase.from('recommendation_settings').update({...payload,updated_at:new Date().toISOString()}).eq('slug',slug);setMsg(error?'Erro ao salvar: '+error.message:'Tudo salvo!')}
function addBtn(){set('buttons',[...(d.buttons||[]),{label:'Saiba mais',type:'link',value:'',message:'Olá! Gostaria de saber mais sobre seus serviços. Encontrei seu contato por meio das Indicações de Luan Maciel.',style:'normal'}])}
function btn(i:number,k:string,v:any){const a=[...(d.buttons||[])];a[i]={...a[i],[k]:v};set('buttons',a)}
function section(si:number,k:string,v:any){const a=structuredClone(d.sections||[]);a[si][k]=v;set('sections',a)}
function item(si:number,ii:number,k:number,v:string){const a=structuredClone(d.sections||[]);a[si].items[ii][k]=v;set('sections',a)}
if(ok===null||!d)return <section className="section"><p>Carregando...</p></section>;if(!ok)return <section className="section"><h1>Acesso restrito</h1></section>;
return <section className="section adminInd"><div className="editorHead"><div><span className="eyebrow">PAINEL</span><h1>Editar indicação</h1><p>Ariane Antério — controle completo da página.</p></div><div className="adminActions"><Link className="viewBtn" href="/indicacoes/procedimentos-esteticos">Ver página</Link><button className="cta" onClick={save}>Salvar tudo</button></div></div>
<div className="editorBox editorGroup"><div className="editorGroupTitle"><span>01</span><div><h2>Cartão em /indicacoes</h2><p>Como esta indicação aparece na lista pública.</p></div></div><label>Título<input value={d.card_title||''} onChange={e=>set('card_title',e.target.value)}/></label><label>Descrição<textarea value={d.card_description||''} onChange={e=>set('card_description',e.target.value)}/></label><label>Cor da capa<input type="color" value={d.card_cover_color||'#1b1719'} onChange={e=>set('card_cover_color',e.target.value)}/></label></div>
<div className="editorBox editorGroup"><div className="editorGroupTitle"><span>02</span><div><h2>Cabeçalho da página</h2><p>Textos principais da página individual.</p></div></div><label>Texto pequeno<input value={d.hero_eyebrow||''} onChange={e=>set('hero_eyebrow',e.target.value)}/></label><label>Título<input value={d.hero_title||''} onChange={e=>set('hero_title',e.target.value)}/></label><label>Descrição<textarea value={d.hero_description||''} onChange={e=>set('hero_description',e.target.value)}/></label></div>
<div className="editorBox editorGroup"><div className="editorGroupTitle"><span>03</span><div><h2>Aparência</h2><p>Cores, fonte, tamanhos e efeitos visuais.</p></div></div><div className="editorGrid"><label>Cor da página<select value={d.theme} onChange={e=>set('theme',e.target.value)}><option value="white">Branca</option><option value="pink">Rosa</option><option value="black">Preta</option><option value="yellow">Amarela</option><option value="blue">Azul</option></select></label><label>Efeito<select value={d.effect} onChange={e=>set('effect',e.target.value)}><option value="none">Sem efeito</option><option value="sparkles">Brilhos caindo</option><option value="flowers">Flores caindo</option></select></label><label>Cor dos textos<input type="color" value={d.text_color} onChange={e=>set('text_color',e.target.value)}/></label><label>Cor dos títulos<input type="color" value={d.heading_color} onChange={e=>set('heading_color',e.target.value)}/></label><label>Fonte<select value={d.font_family} onChange={e=>set('font_family',e.target.value)}><option value="system">Padrão</option><option value="serif">Clássica</option><option value="rounded">Arredondada</option><option value="mono">Monoespaçada</option></select></label><label>Tamanho do título ({d.title_size}px)<input type="range" min="30" max="90" value={d.title_size} onChange={e=>set('title_size',+e.target.value)}/></label><label>Tamanho dos textos ({d.body_size}px)<input type="range" min="13" max="28" value={d.body_size} onChange={e=>set('body_size',+e.target.value)}/></label></div></div>
<div className="editorBox editorGroup"><div className="editorGroupTitle"><span>04</span><div><h2>Conteúdo da indicação</h2><p>Edite seções, procedimentos e descrições.</p></div></div><div className="boxHead"><h2>Seções e procedimentos</h2><button onClick={()=>set('sections',[...(d.sections||[]),{title:'Nova seção',items:[]}])}>+ Seção</button></div>{(d.sections||[]).map((s:any,si:number)=><div className="sectionEditor" key={si}><div className="inlineEdit"><input value={s.title} onChange={e=>section(si,'title',e.target.value)}/><button onClick={()=>set('sections',d.sections.filter((_:any,i:number)=>i!==si))}>Remover seção</button></div>{s.items.map((it:string[],ii:number)=><div className="itemEdit" key={ii}><input placeholder="Título" value={it[0]} onChange={e=>item(si,ii,0,e.target.value)}/><input placeholder="Descrição" value={it[1]} onChange={e=>item(si,ii,1,e.target.value)}/><button onClick={()=>{const a=structuredClone(d.sections);a[si].items.splice(ii,1);set('sections',a)}}>×</button></div>)}<button onClick={()=>{const a=structuredClone(d.sections);a[si].items.push(['Novo item','']);set('sections',a)}}>+ Adicionar item</button></div>)}</div>
<div className="editorBox editorGroup"><div className="editorGroupTitle"><span>05</span><div><h2>Botões e contato</h2><p>Crie chamadas para links externos ou WhatsApp.</p></div></div><div className="boxHead"><h2>Botões</h2><button onClick={addBtn}>+ Criar botão</button></div>{(d.buttons||[]).map((b:Btn,i:number)=><div className="buttonEditor" key={i}><input placeholder="Texto: Saiba mais / Chamar aqui" value={b.label} onChange={e=>btn(i,'label',e.target.value)}/><select value={b.type} onChange={e=>btn(i,'type',e.target.value)}><option value="link">Link externo</option><option value="whatsapp">WhatsApp</option></select><input placeholder={b.type==='whatsapp'?'Número com DDD':'https://...'} value={b.value} onChange={e=>btn(i,'value',e.target.value)}/>{b.type==='whatsapp'&&<textarea placeholder="Mensagem pronta" value={b.message||''} onChange={e=>btn(i,'message',e.target.value)}/>}<select value={b.style} onChange={e=>btn(i,'style',e.target.value)}><option value="normal">Normal</option><option value="pulse">Pulsar</option><option value="float">Flutuar</option><option value="shine">Brilho passando</option><option value="grow">Crescer suave</option><option value="border">Borda animada</option><option value="super-glow">Super brilho</option><option value="super-pulse">Super pulsar</option><option value="super-shimmer">Super destaque</option></select><button onClick={()=>set('buttons',d.buttons.filter((_:any,x:number)=>x!==i))}>Remover botão</button></div>)}</div>
<button className="cta bottomSave" onClick={save}>Salvar alterações</button>{msg&&<p className="saveMsg">{msg}</p>}</section>}