'use client';import {useEffect,useState} from 'react';import {supabase} from '../../lib/supabase';
type Btn={id?:number,label:string,url:string,action_type:string,background_color:string,text_color:string,border_color:string,animation:string,sort_order:number,active:boolean};
const empty:Btn={label:'Novo botão',url:'',action_type:'external',background_color:'#0d1b2a',text_color:'#ffffff',border_color:'#c89b3c',animation:'none',sort_order:0,active:true};
export default function Admin(){const[ok,setOk]=useState<boolean|null>(null);const[buttons,setButtons]=useState<Btn[]>([]);const[title,setTitle]=useState('Luan Maciel de Lemos');const[sub,setSub]=useState('');const[msg,setMsg]=useState('');
async function load(){const{data:{user}}=await supabase.auth.getUser();if(!user){setOk(false);return}const{data:a}=await supabase.rpc('is_site_admin');if(!a){setOk(false);return}setOk(true);const{s:dataS}=await (async()=>{const r=await supabase.from('hotsite_settings').select('*').eq('id',1).single();return{s:r.data}})();if(dataS){setTitle(dataS.title);setSub(dataS.subtitle||'')}const{data:b}=await supabase.from('hotsite_buttons').select('*').order('sort_order');setButtons(b||[])}
useEffect(()=>{load()},[]);
async function saveSettings(){setMsg('Salvando...');const{error}=await supabase.from('hotsite_settings').update({title,subtitle:sub,updated_at:new Date().toISOString()}).eq('id',1);setMsg(error?'Erro ao salvar.':'Hotsite salvo!')}
async function saveBtn(b:Btn){setMsg('Salvando botão...');const payload={label:b.label,url:b.url,action_type:b.action_type,background_color:b.background_color,text_color:b.text_color,border_color:b.border_color,animation:b.animation,sort_order:b.sort_order,active:b.active};let error;if(b.id){({error}=await supabase.from('hotsite_buttons').update(payload).eq('id',b.id))}else{({error}=await supabase.from('hotsite_buttons').insert(payload))}setMsg(error?'Erro ao salvar botão.':'Botão salvo!');await load()}
async function del(id?:number){if(!id)return;await supabase.from('hotsite_buttons').delete().eq('id',id);await load()}
if(ok===null)return <section className="section"><p>Verificando acesso...</p></section>;if(!ok)return <section className="section"><h1>Acesso restrito</h1><p>Entre com a conta de administrador.</p></section>;
return <section className="section"><h1>Painel do administrador</h1><div className="cards"><div className="card"><h2>Análises</h2><p>Hoje • 7 dias • mês • ano • sempre</p></div><div className="card"><h2>Editar site</h2><p>Informações, páginas e contato.</p></div></div><div className="adminbox"><h2>Editar Hotsite /aqui</h2><p>Esta página não aparece no menu principal. Configure abaixo o que será mostrado nela.</p><label>Título<input value={title} onChange={e=>setTitle(e.target.value)}/></label><label>Descrição<input value={sub} onChange={e=>setSub(e.target.value)}/></label><button className="cta" onClick={saveSettings}>Salvar informações</button><h3>Botões</h3>{[...buttons,empty].map((b,i)=><div className="buttonEditor" key={b.id??'new'}><label>Texto<input value={b.label} onChange={e=>{const a=[...buttons];if(b.id){a[i]={...b,label:e.target.value};setButtons(a)}else setButtons([...buttons,{...empty,label:e.target.value}])}}/></label><label>Link<input value={b.url} onChange={e=>{if(b.id){const a=[...buttons];a[i]={...b,url:e.target.value};setButtons(a)}}} placeholder="https://..."/></label><label>Função<select value={b.action_type} onChange={e=>{if(b.id){const a=[...buttons];a[i]={...b,action_type:e.target.value};setButtons(a)}}}><option value="external">Link externo</option><option value="doacao">Doação</option><option value="oferta">Oferta</option><option value="compra">Compra</option></select></label><label>Animação<select value={b.animation} onChange={e=>{if(b.id){const a=[...buttons];a[i]={...b,animation:e.target.value};setButtons(a)}}}><option value="none">Sem animação</option><option value="blink">Piscando</option><option value="shake">Tremendo</option><option value="pulse">Pulsando</option><option value="glow">Acendendo</option><option value="float">Flutuando</option></select></label><div className="colorRow"><label>Cor<input type="color" value={b.background_color}/></label><label>Texto<input type="color" value={b.text_color}/></label><label>Contorno<input type="color" value={b.border_color}/></label></div><label>Ordem<input type="number" value={b.sort_order} onChange={e=>{if(b.id){const a=[...buttons];a[i]={...b,sort_order:Number(e.target.value)};setButtons(a)}}}/></label><button className="cta" onClick={()=>saveBtn(b)}>{b.id?'Salvar botão':'Adicionar botão'}</button>{b.id&&<button className="danger" onClick={()=>del(b.id)}>Excluir</button>}</div>)}{msg&&<p><b>{msg}</b></p>}<p><a href="/aqui">Abrir Hotsite →</a></p></div></section>}