import Link from 'next/link';

const facial=[
['Limpeza de Pele','Higieniza e revitaliza.'],['Peeling de Diamante','Renova e suaviza.'],['Peeling Elétrico','Renova e uniformiza.'],['Dermaplaning','Remove células mortas e penugens.'],['Microagulhamento','Estimula colágeno.'],['Peeling de Hollywood','Ilumina e uniformiza.'],['Radiofrequência Facial','Estimula colágeno.'],['Jato de Plasma','Trata lesões e marcas.'],['Alta Frequência','Auxilia no controle da oleosidade.'],['Lipo de Papada Enzimática','Auxilia na redução da papada.'],['Hidrolipoclasia de Papada','Auxilia na redução da gordura.']];
const corporal=[
['Criolipólise de Placa','Reduz gordura localizada.'],['Lipoenzimática','Atua na gordura localizada.'],['Hidrolipoclasia','Auxilia na gordura localizada.'],['Drenagem Linfática','Estimula a circulação e reduz retenção.'],['Massagem Modeladora com Endermo','Modela e ativa a circulação.'],['Manta Térmica','Promove aquecimento e sudorese.'],['Pump Glúteo','Estimula a musculatura.'],['Eletroterapia','Auxilia na tonificação muscular.'],['Tratamento para Lipedema','Auxilia na circulação e edema.'],['Tratamento de Estrias','Estimula a renovação da pele.']];
const pos=[['Pós-Operatório','Auxilia na recuperação.'],['Pós-Operatório Pós-Parto','Auxilia na recuperação e redução de retenção.'],['Aplicação de Tape','Auxilia no suporte e recuperação.'],['Aplicação de Tape Pós-Parto','Auxilia no suporte e conforto.'],['Drenagem Linfática para Gestante','Auxilia na circulação e redução de retenção.']];
const laser=[['Epilação a Laser','Redução progressiva dos pelos.'],['Clareamento a Laser','Axilas, virilha e outras áreas.'],['Remoção de Tatuagem',''],['Remoção de Sobrancelha','']];
const especiais=[['PEIM','Tratamento de microvasos.'],['Remoção de Verrugas, Fibromas Moles, Acrocórdons, Xantelasma e outras lesões','']];
function Grupo({titulo,itens}:{titulo:string,itens:string[][]}){return <section className="indGrupo"><h2>{titulo}</h2><div>{itens.map(([n,d])=><p key={n}><strong>{n}</strong>{d&&<> — {d}</>}</p>)}</div></section>}
export default function IndicacaoProcedimentos(){return <main className="indicacaoPage"><Link href="/indicacoes" className="indicBack">← Voltar para Indicações</Link><header className="indicHero"><div className="indicHeroText"><span>INDICAÇÃO • ESTÉTICA E BEM-ESTAR</span><h1>Procedimentos Estéticos</h1><p>Conheça os procedimentos faciais, corporais, pós-operatórios, laser e tratamentos específicos disponíveis.</p></div></header><div className="indicContent"><Grupo titulo="✨ FACIAL" itens={facial}/><Grupo titulo="CORPORAL" itens={corporal}/><Grupo titulo="🌸 PÓS-OPERATÓRIO E PÓS-PARTO" itens={pos}/><Grupo titulo="🌸 LASER" itens={laser}/><Grupo titulo="💉 PROCEDIMENTOS ESPECÍFICOS" itens={especiais}/><div className="indicNotice">Para informações sobre indicação, contraindicação, riscos e cuidados de cada procedimento, consulte o profissional responsável.</div></div></main>}